
WAITING_FOR_NAME_EMPIRE = 1
CONFIRMATION_NAME_EMPIRE = 2


WAITING_ID_ATTACKING_EMPIRE = 1
WAITING_COUNT_UNITS_ATTACKING_EMPIRE = 2
CONFIRMATION_FOR_ATTACK_EMPIRE = 3


WAITING_ID_ESPIONAGE_EMPIRE = 1
WAITING_COUNT_UNITS_ESPIONAGE_EMPIRE = 2
CONFIRMATION_FOR_ESPIONAGE_EMPIRE = 3


WAITING_RADIUS_FOR_EXPLORATION = 1
WAITING_COUNT_UNITS_EXPLORATION = 2
CONFIRMATION_FOR_EXPLORATION_EMPIRE = 3


CHOOSE_RESOURCE = 1
ASK_QUANTITY = 2


WAITING_COUNT_UNITS_ATTACKING_LOCATION = 1
CONFIRMATION_FOR_ATTACK_LOCATION = 2


WAITING_COUNT_UNITS_PLACE_GARRISON = 1
CONFIRMATION_FOR_UNITS_PLACE_GARRISON = 2
